language: python
branches:
  only:
  - master
install:
- pip install pelican ghp-import
script:
- make github
addons:
    apt:
        packages:
            - language-pack-fr
env:
  global:
    - LANG=fr_FR.UTF-8
    - LC_ALL=fr_FR.UTF-8
